### ISSUE TITLE
Werden bald auch Krankenhausaufnahmen im Dataset inkludiert?

### ISSUE THREAD

**Issue by corneliusroemer** [robert-koch-institut/SARS-CoV-2_Infektionen_in_Deutschland#1]
Neben Daten zu Fällen und Todesfällen sollten jetzt auch Daten zu Krankenhausaufnahmen vorhanden sein, im gleichen Detailgrad. Gibt es Pläne, diese Daten hier zu integrieren?

**Comment by RKIOpenData** [comment]
Hallo @corneliusroemer,

wir sind derzeit in Abstimmung darüber wie wir die Daten der Krankenhausaufnahmen bereitstellen. 
Ich muss daher noch um etwas Geduld bitten, danke aber für die Anregung die Daten in den vorhandenen Datensatz zu integrieren.

Mit besten Grüßen 
@HannesWuensche
für das Team RKI | Open Data
