### ISSUE TITLE
Landkreis Informationen als CSV?

### ISSUE THREAD

**Issue by matthiasgeihs** [robert-koch-institut/SARS-CoV-2_Infektionen_in_Deutschland#12]
Gibt es die Landkreisnamen nach Landkreis ID als CSV (oder anderweitig einfach lesbares Format)?

Z.B. so wie im README angedeutet:

| IdLandkreis | Bezirk |
| ----------- | ------ |
|11001 | Berlin Mitte | 
|11002 | Berlin Friedrichshain-Kreuzberg | 
|11003 | Berlin Pankow | 
|11004 | Berlin Charlottenburg-Wilmersdorf| 
|11005 | Berlin Spandau | 
|11006 | Berlin Steglitz-Zehlendorf |
...

**Comment by runbikeswim** [comment]
Über https://opendata.arcgis.com/datasets/917fc37a709542548cc3be077a786c17_0 kann eine CSV-Datei heruntergeladen werden, die unter anderem Spalten für die Lankreis-ID und den Namen des Landkreises enthält

**Comment by matthiasgeihs** [comment]
> Über https://opendata.arcgis.com/datasets/917fc37a709542548cc3be077a786c17_0 kann eine CSV-Datei heruntergeladen werden, die unter anderem Spalten für die Lankreis-ID und den Namen des Landkreises enthält

Danke, danach habe ich gesucht.
