### ISSUE TITLE
Wann wurde Eintrag in Datenbank hinzugefügt?

### ISSUE THREAD

**Issue by matthiasgeihs** [robert-koch-institut/SARS-CoV-2_Infektionen_in_Deutschland#13]
Gibt es die Möglichkeit in den Daten aufzunehmen wann ein Eintrag im CSV hinzugefügt wurde? (Und falls es vorkommt, dass Einträge nachträglich angepasst werden, wann der Eintrag zuletzt geändert wurde.)

In diesem Fall könnte man einfach feststellen, wie viele neue Einträge an einem Tag hinzugekommen sind.

**Comment by HannesWuensche** [comment]
Hallo @matthiasgeihs ,

Neue Einträge werden durch NeuerFall = `1` gekennzeichnet. Dies solle eine die Feststellung, wie viele neue Einträge an einem Tag hinzugekommen sind, ermöglichen. 

Mit besten Grüßen
@HannesWuensche
für das Team RKI | Open Data

**Comment by matthiasgeihs** [comment]
Hallo @HannesWuensche , vielen Dank für die Erklärung. Das bedeutet, dass man für den aktuellen Datensatz demnach nachvollziehen kann, welche Einträge in der letzten Revision dazugekommen. Das ist hilfreich.

Noch informativer wäre es, wenn die Spalte statt einem binären Wert, einen Datumswert hätte, der angibt wann Eintrag hinzugefügt wurde. Dann könnte man auch retrospektiv einfach nachvollziehen, wie viele Einträge an welchen Tagen hinzugekommen sind. Gibt es dazu schon Überlegungen? (Prinzipiell könnte man das natürlich auch durch die Git History zurückrechnen, was aber sehr viel aufwändiger wäre.)

Vielen Dank und beste Grüße zurück,
Matthias

**Comment by HannesWuensche** [comment]
Hallo @matthiasgeihs,

leider ist der Wert nicht nur binär, sondern kann neben `0` und `1` auch den Wert `-1` annehmen (wenn eine Korrektur vorliegt).
Weiterhin können Fallgruppen verschmelzen, sodass an verschiedenen Tagen berichtete Fälle, später in einer Gruppe zu finden sind. Für eine Übersicht wann welche Fallgruppen aufgenommen ("berichtet") wurden bleibt daher nur der Vergleich der Daten der entsprechenden Tage (um dies zu vereinfachen stellen wir unter anderem das Archiv zur Verfügung). 

Mit besten Grüßen
@HannesWuensche
für das Team RKI | Open Data
