### ISSUE TITLE
Fehlerhafte Dokumentation bezüglich der Ausprägung der Altersgruppen

### ISSUE THREAD

**Issue by akulisch** [robert-koch-institut/SARS-CoV-2_Infektionen_in_Deutschland#14]
In der Dokumentation steht Folgendes zu der Ausprägung der Altersgruppen:
A00-04, A05-14, A15-A34, A35-A59, A60-A79, A80+, unbekannt
Die ersten beiden dieser Angaben sind allerdings inkorrekt, da diese auch dem Schema der anderen folgen und A00-A04 bzw. A05-A14 lauten müssten.

**Comment by HannesWuensche** [comment]
Hallo @akulisch,

vielen Dank für den Hinweis. 
Der Fehler ist behoben. 

Mit besten Grüßen
@HannesWuensche
für das Team RKI | Open Data
