### ISSUE TITLE
7-Tage Inzidenz als Spalte hinzufügen

### ISSUE THREAD

**Issue by kenspeckle1** [robert-koch-institut/SARS-CoV-2_Infektionen_in_Deutschland#15]
Gibt es die Möglichkeit, dass die 7-Tage Inzidenz als weitere Spalte mit aufgenommen wird oder aber die Excel-Dateien mit den 7-Tage Inzidenzen [(1)](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Inzidenz-Tabellen.html) ein eigenes Repository bekommen?
Als CSV-Datei wären die Daten viel einfacher zu verarbeiten als die Excel-Dateien.

**Comment by HannesWuensche** [comment]
Hallo @kenspeckle1,

wir überlegen derzeit die 7-Tage Inzidenzen als eigenes Repositorium anzubieten bzw. per Action aus den Infektionszahlen zu erzeugen. Eine Erweiterung der  *Deutschland_SarsCov2_Infektionen.csv kommt für uns nicht in frage. 
Leider wird die Erweiterung der Daten noch etwas Zeit in Anspruch nehmen, wir bitten daher um Geduld. 

Mit besten Grüßen
@HannesWuensche
für das Team RKI | Open Data
