### ISSUE TITLE
Datenstand als Spalte in den Dateien

### ISSUE THREAD

**Issue by benne71** [robert-koch-institut/SARS-CoV-2_Infektionen_in_Deutschland#16]
Gibt es einen Grund, weshalb der Datenstand nur im Dateinamen und nicht als eigene Spalte IN den Dateien vorliegt?
Die Weiterverarbeitung als Zeitreihe wäre so bedeutend einfacher.

**Comment by HannesWuensche** [comment]
Hallo @benne71,

wir versuchen die Größe der Dateien möglichst klein zu halten. 
Eine Spalte die nur den Datenstand enthält würde die Datei unnötig vergrößern. 

Wir überlegen derzeit, den Datenstand als Kommentar ans Ende der .csv Dateien zu schreiben. Jedoch sind wir hierzu noch in Abstimmung. 

Mit besten Grüßen
@HannesWuensche
für das Team RKI | Open Data
