### ISSUE TITLE
Unvollständiger Datenstand 2021-12-09

### ISSUE THREAD

**Issue by Tho-Mat** [robert-koch-institut/SARS-CoV-2_Infektionen_in_Deutschland#17]
Keine Daten vom 8.12.2021 enthalten.
Sieht aus als wenn es die Daten von Gestern sind.

**Comment by HannesWuensche** [comment]
Hallo @Tho-Mat,

vielen Dank für die Rückmeldung. 
Wie beschreiben, sind die heute veröffentlichten Daten unvollständig. Wir arbeiten derzeit mit Hochdruck an der Behebung des Fehlers und versuchen schnellstmöglich  den vollständigen Datensatz zu veröffentlichen. 

Mit besten Grüßen
@HannesWuensche
für das Team RKI | Open Data

**Comment by HannesWuensche** [comment]
Hallo @Tho-Mat,

der Fehler ist behoben und die Daten nun vollständig.
Vielen Danke für das aufmerksame Verfolgen des Datensatzes. 

Mit besten Grüßen
@HannesWuensche
für das Team RKI | Open Data

**Comment by Tho-Mat** [comment]
Als einfache Vorprüfung könnte man das Hochladen der Daten unterbinden, wenn sich die Dateigröße nicht erhöht.
