### ISSUE TITLE
Mögliche Auswirkungen der fehlenden Daten von Eisenach auf die Gesamtfallzahlen

### ISSUE THREAD

**Issue by MaHi84** [robert-koch-institut/SARS-CoV-2_Infektionen_in_Deutschland#18]
Die Stadt Eisenach (IdLandkreis: 16056) wurde zur Jahresmitte in den Landkreis Wartburgkreis eingegliedert. So wie es ausschaut, sind im aktuellen Datensatz auch keine historischen Daten mehr enthalten.

Die Infektionen/Todesfälle/etc. gab es ja trotzdem und dürften sich auch nur unter Berücksichtigung derer, mit den Gesamtfallzahlen im RKI-Dashboard decken.

**Comment by MaHi84** [comment]
Habe eben mal nachgerechnet. Die Summe des aktuellen Datensatzes deckt sich mit den Zahlen des RKI's.

Trotzdem die Frage: Ist die Gesamtzahl der Infektionen (…) so überhaupt noch richtig, nachdem man die Altdaten zur Landkreis-ID 16056 von Eisenach vollständig aus dem Datensatz entfernt hat oder wurden die damaligen Fälle anderweitig wo hinzuaddiert?

**Comment by HannesWuensche** [comment]
Hallo @MaHi84,

vielen Dank für die Nachfrage bzw. den Hinweis. 

Ich werde die Anfrage an die inhaltlich zuständigen Kolleg:innen weiterleiten. 
Aufgrund der Weihnachtstage wird die Beantwortung der Frage jedoch etwas länger dauern. 

Mit besten Grüßen
@HannesWuensche
für das Team RKI | Open Data

**Comment by HannesWuensche** [comment]
Hallo @MaHi84,

in den historischen Datenständen ist der SK Eisenach natürlich nach wie vor enthalten. 

Wie sie richtig vermuten sind, mit der Eingliederung zum 1. Juli 2021 in den Wartburgkreis, die in der Zeitreihe zurückliegenden Meldungen des SK Eisenach dem Wartburgkreis zugeordnet worden. Es sind daher keine Meldungen verlorengegangen. 

Mit besten Grüßen
@HannesWuensche
für das Team RKI | Open Data
