### ISSUE TITLE
Neu gemeldete Infektionen zu Beginn (ersten 30/31 Tage) der Pandemie

### ISSUE THREAD

**Issue by SamrawitGashawAsefa** [robert-koch-institut/SARS-CoV-2_Infektionen_in_Deutschland#19]
Hallo, 

im Rahmen meiner Masterarbeit bräuchte ich Daten, die weiter zurück liegen und wäre sehr dankbar, wenn mir jemand diese zur Verfügung stellen könnte oder sagen kann, wo man diese findet.
Nötig wäre die Anzahl der gemeldeten Neuinfektionen pro Tag und die Anzahl an Genesenen, zu Beginn der Pandemie. Mit Beginn ist der erste gemeldete Fall gemeint und die 30/31 darauffolgenden Tage.

Vielen herzlichen Dank im Voraus.

Viele Grüße und Gesundheit, 
Samrawit Gashaw

**Comment by HannesWuensche** [comment]
Hallo @SamrawitGashawAsefa,

Bevor wir unsere Daten auf Github bereitgestellt haben, wurde bereits von @MichaelKreil eine Archiv mit unseren Daten gepflegt: https://github.com/ard-data/2020-rki-archive

Ich hoffe dieses hilft ihnen weiter. 

Mit besten Grüßen
@HannesWuensche 
für das Team RKI | Open Data

**Comment by SamrawitGashawAsefa** [comment]
Vielen herzlichen Dank!

Viele Grüße, 
Samrawit Gashaw
