### ISSUE TITLE
Wie kann ich eine Zeitreihe der Aktiven Fälle (zum jeweiligen Tag) erstellen?

### ISSUE THREAD

**Issue by BrunnerBI** [robert-koch-institut/SARS-CoV-2_Infektionen_in_Deutschland#2]
Wie kann ich eine Zeitreihe der Aktiven Fälle (zum jeweiligen Datum) erstellen?

Ich Blick bei dieser Korrektur Logik nicht durch und weiß nicht wie ich die Filter setzen muss...

Any help would be appreciated

**Comment by HannesWuensche** [comment]
Hallo @BrunnerBI ,

Für eine detaillierte Auskunft zu Inhaltlichen Fragen muss ich sie an die Kolleginn:en des  [Fachgebiets 31](https://www.rki.de/DE/Content/Institut/OrgEinheiten/Abt3/FG31/FG31_node.html) verweisen. Diese erreichen sie über [info@rki.de](mailto:info@rki.de), wo alle Anfragen sortiert und weitergeleitet werden. 

Dennoch ein kurzer Lösungsversuch von meiner Seite (leider ohne Garantie auf Korrektheit):

Die aktiven Fälle eines Tages lassen sich nur aus den Daten des jeweiligen Tages auslesen. Die Anzahl der aktive Fälle sollte dann der Summe der nicht als genesen oder verstorben gemeldeten (NeuerTodesfall, NeuGenesen = -9) Fälle entsprechen. 
Für das Erstellen einer Zeitreihe können sie auf die Daten des [Archivs](https://github.com/robert-koch-institut/SARS-CoV-2_Infektionen_in_Deutschland/tree/master/Archiv) zurückgreifen. 

Mit bestem Grüßen!
@HannesWuensche
für das Team RKI | Open Data

**Comment by BrunnerBI** [comment]
Danke Herr Wuensche, das hatte ich schon befürchtet. Aufgrund der Datenmenge ist das aber alles andere als praktikabel. Da müsste man jeden Tag mehrere GBs laden...

Danke aber für die Antwort.

**Comment by HannesWuensche** [comment]
Hallo @BrunnerBI ,

da die aktuellen Daten derzeit nur um die 100MB groß sind sollte der tägliche Download z.b. mit [git](https://git-scm.com/downloads) nicht viel größer sein. Die Daten des Archivs ändern sich ja nicht mehr und müssen daher auch nicht erneut heruntergeladen werden. 

Mit bestem Grüßen!
@HannesWuensche
für das Team RKI | Open Data
