### ISSUE TITLE
Fehler in Readme.md bzgl. Ausprägung/Erläuterung für AnzahlFall, AnzahlTodesfall, AnzahlGenesen

### ISSUE THREAD

**Issue by runbikeswim** [robert-koch-institut/SARS-CoV-2_Infektionen_in_Deutschland#4]
In der Datei `Readme.md` sind im Abschnitt **Merkmalsausprägung** in der Zeile _AnzahlFall_ folgende Angaben falsch bzw. irreführend:
 - Spalte _Ausprägung_: Da in den Datensätzen auch negative Werte auftreten, sollte hier _Ganzzahlig_ statt _Natürliche Zahl_ stehen.
 - Spalte _Erläuterung_: In den vorhandenen Daten ist _AnzahlFall_ < 0 genau dann, wenn _NeuerFall_ = -1 ist. Die Zahlen sind also nicht als negativ zu interpretieren, denn sie **sind** negativ. 
 Wenn man diese Zahlen als Korrekturen interpretiert, d.h. mit ihrem (negativen) Vorzeichen auf die positiven Werte von _AnzahlFall_ addiert, weicht das Ergebnis stark von dem Wert ab, der im Dashboard (https://corona.rki.de/) angezeigt wird. 
 Wenn man dagegen die negativen Fallzahlen ignoriert, d.h. für die Summe der Fälle nur die Werte berücksichtigt, die größer als Null sind, erhält man den Wert, der mit der Angabe im Dashboard übereinstimmt.
 
Das gleiche gilt für die Zeilen _AnzahlTodesfall_ und _AnzahlGenesen_. 

Eine Auswertung der Daten ist unter https://github.com/runbikeswim/RKI-COVID-15-Data-Sources-Analysis zu finden.

**Comment by HannesWuensche** [comment]
Lieber @runbikeswim,

vielen Dank für ihre Anmerkung zur Ausprägung und Erläuterung der Variablen AnzahlFall, AnzahlGenesen und AnzahlTodesfall. Hier war tatsächlich ein Fehler in der Dokumentation. Wir haben die entsprechenden Einträge den Anmerkungen folgend aktualisiert. Nochmals: Danke!

Mit besten Grüßen
@HannesWuensche
für das Team RKI | Open Data
