### ISSUE TITLE
Todesfälle pro Monat sind inkonsistent mit anderen Daten

### ISSUE THREAD

**Issue by Byggvir** [robert-koch-institut/SARS-CoV-2_Infektionen_in_Deutschland#8]
Die Todesfälle pro Monat stimmen nicht annähernd mit den Todesfällen pro Monat aus der Tabelle unter
https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Projekte_RKI/COVID-19_Todesfaelle.html überein.

Stand: GitHub 2021-11-05

SterbeMonat | Anzahl verstorbene COVID-19 Fälle | GitHub | Delta
-- | -- | -- | --
2020m3 | 1120 | 2682 | -1562
2020m4 | 6068 | 5727 | 341
2020m5 | 1575 | 697 | 878
2020m6 | 315 | 148 | 167
2020m7 | 134 | 144 | -10
2020m8 | 152 | 119 | 33
2020m9 | 205 | 342 | -137
2020m10 | 1488 | 3240 | -1752
2020m11 | 8592 | 11897 | -3305
2020m12 | 21951 | 25952 | -4001
2021m1 | 21831 | 19358 | 2473
2021m2 | 9749 | 6585 | 3164
2021m3 | 5492 | 5742 | -250
2021m4 | 6500 | 6586 | -86
2021m5 | 4678 | 2599 | 2079
2021m6 | 1074 | 266 | 808
2021m7 | 260 | 163 | 97
2021m8 | 473 | 894 | -421
2021m9 | 1521 | 1565 | -44
2021m10 | 893 | 1579 | -686
2021m11 | 0 | 56 | -
Summe | 94071 | 96285 | -2214

**Comment by HannesWuensche** [comment]
Hallo Byggvir,

vielen Dank für die Anfrage und den Hinweis. Wir sind in Kontakt mit den zuständigen Kolleg:innen und schauen uns die Diskrepanz in den Zahlen näher an. 

Mit besten Grüßen
@HannesWuensche
für das Team RKI | Open Data

**Comment by HannesWuensche** [comment]
Hallo @Byggvir,

Im Datensatz "SARS-CoV-2 Infektionen in Deutschland" stellen wir keine Sterbedaten bereit, sondern geben nur an, wenn Fälle als verstorben gemeldet wurden. Eine Aussage über das Sterbedatum ist nicht enthalten. Eine sichere Angabe der Fallzahlen nach Sterbemonat ist daher nicht möglich. 

Darüber hinaus kann es zu Abweichung gegenüber anderen Datenquellen kommen, da verschiedene Meldesysteme verwendet werden. Die zum Vergleich herangezogenen Anzahlen werden durch eine Sonderauswertung des Statistischen Bundesamtes bereitgestellt, siehe hierzu: https://www.destatis.de/DE/Themen/Gesellschaft-Umwelt/Bevoelkerung/Sterbefaelle-Lebenserwartung/sterbefallzahlen.html 

Eine weitere Ursache für die dargestellte Abweichung (ca. 2%) kann durch die Sicherheitsfrist der Veröffentlichung, von knapp 3 Wochen, entstehen. Die Entsprechenden Angaben sind im Tabellenblatt "Erläuterungen" der zitierten [Tabelle](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Projekte_RKI/COVID-19_Todesfaelle.html) zu entnehmen.

Mit besten Grüßen
@HannesWuensche
für das Team RKI | Open Data
