### ISSUE TITLE
Ältere Datensätze vor April 2021

### ISSUE THREAD

**Issue by kohlrabi** [robert-koch-institut/SARS-CoV-2_Infektionen_in_Deutschland#9]
Hallo,

gibt es noch irgendwo ein Repository mit älteren Datensätzen vor dem April 2021?

Danke.

Grüße,
Christoph

**Comment by HannesWuensche** [comment]
Hallo Christoph,

es gibt ein von @MichaelKreil gepflegtes Github Archiv mit den Daten von 2020:

https://github.com/ard-data/2020-rki-archive 

Die Anfrage zur Datenbereitstellung vor dem 2021-04-02 ist an meine Kolleg:innen weitergegeben. Aufgrund des nach wie vor hohen Arbeitsaufwands im Zusammenhang mit der Pandemie können wir aber derzeit keine Aussage zur Umsetzung der Anfrage treffen. 

Mit besten Grüßen
@HannesWuensche
für das Team RKI | Open Data

**Comment by kohlrabi** [comment]
Hallo Hannes,

danke dir, ich werde mir das Arhiv mal anschauen. Wenn dort alle Daten zu finden sind, ist das ja völlig ausreichend.


Grüße,
Christoph
